export default [
  {
    matched_terms: [],
    data: {
      id: "ACCES00222-glen plaid - pumpkin spice",
      url: "silk-necktie-acces00222",
      stores: ["Bonobos"],
      swatches: [
        {
          on_sale: false,
          markdown: false,
          inventory: 106,
          color_name: "glen plaid - pumpkin spice",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 79,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/259475/original/TIE_NECKTIE_BTE11128XO3308_swatch.jpg?1660071624=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/264471/original/TIE_NECKTIE_BTE11128XO3308_40_outfitter.jpg?1661351204=",
          color_presentation: "Glen Plaid Pumpkin Spice",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 369,
          color_name: "navy",
          final_sale: false,
          full_price: 89,
          purchasable: true,
          current_price: 89,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/247176/original/TIE_NECKTIE_16735-BLK02_swatch.jpg?1651161471=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/247177/original/TIE_NECKTIE_16735-BLK02_40_category-outfitter.jpg?1651161589=",
          color_presentation: "Navy",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 315,
          color_name: "matte black",
          final_sale: false,
          full_price: 89,
          purchasable: true,
          current_price: 89,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/82229/original/Ties_Tie_21248-BK524_swatch.jpg?1541104693=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232995/original/TIE_NECKTIE_21248-BK524_40_category-outfitter.jpg?1637363791=",
          color_presentation: "Matte Black",
        },
        {
          on_sale: true,
          markdown: true,
          inventory: 30,
          color_name: "purple gingham",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 59,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245131/original/TIE_NECKTIE_BTE11128XP2693_swatch.jpg?1649429477=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245303/original/TIE_NECKTIE_BTE11128XP2693_40_category-outfitter.jpg?1649686737=",
          color_presentation: "Purple Gingham",
        },
        {
          on_sale: true,
          markdown: true,
          inventory: 15,
          color_name: "navy dinosaurs",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 59,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245119/original/TIE_NECKTIE_BTE11128XN2692_swatch.jpg?1649429242=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245297/original/TIE_NECKTIE_BTE11128XN2692_40_category-outfitter.jpg?1649686702=",
          color_presentation: "Navy Dinosaurs",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 14,
          color_name: "navy teal floral",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 79,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245109/original/TIE_NECKTIE_BTE11128XN2694_swatch.jpg?1649429039=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245299/original/TIE_NECKTIE_BTE11128XN2694_40_category-outfitter.jpg?1649686714=",
          color_presentation: "Navy Teal Floral",
        },
        {
          on_sale: true,
          markdown: true,
          inventory: 85,
          color_name: "navy teal dots",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 59,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245117/original/TIE_NECKTIE_BTE11128XG2706_swatch.jpg?1649429201=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245295/original/TIE_NECKTIE_BTE11128XG2706_40_category-outfitter.jpg?1649686692=",
          color_presentation: "Navy Teal Dots",
        },
      ],
      is_bundle: false,
      image_url:
        "https://bonobos-prod-s3.imgix.net/products/264471/original/TIE_NECKTIE_BTE11128XO3308_40_outfitter.jpg?1661351204=",
      color_name: "glen plaid - pumpkin spice",
      full_price: 79,
      final_sale: false,
      description:
        "Pair it with your favorite suit & you'll have an impeccably sharp, highly handsome ensemble.",
      is_gift_card: false,
      is_new_color: true,
      current_price: 79,
      number_of_fits: 0,
      is_new_program: false,
      markdown_swatches: [
        {
          on_sale: true,
          markdown: true,
          inventory: 30,
          color_name: "purple gingham",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 59,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245131/original/TIE_NECKTIE_BTE11128XP2693_swatch.jpg?1649429477=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245303/original/TIE_NECKTIE_BTE11128XP2693_40_category-outfitter.jpg?1649686737=",
          color_presentation: "Purple Gingham",
        },
        {
          on_sale: true,
          markdown: true,
          inventory: 15,
          color_name: "navy dinosaurs",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 59,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245119/original/TIE_NECKTIE_BTE11128XN2692_swatch.jpg?1649429242=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245297/original/TIE_NECKTIE_BTE11128XN2692_40_category-outfitter.jpg?1649686702=",
          color_presentation: "Navy Dinosaurs",
        },
        {
          on_sale: true,
          markdown: true,
          inventory: 85,
          color_name: "navy teal dots",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 59,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245117/original/TIE_NECKTIE_BTE11128XG2706_swatch.jpg?1649429201=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245295/original/TIE_NECKTIE_BTE11128XG2706_40_category-outfitter.jpg?1649686692=",
          color_presentation: "Navy Teal Dots",
        },
        {
          on_sale: true,
          markdown: true,
          inventory: 87,
          color_name: "yellow blue stripe",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 59,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245135/original/TIE_NECKTIE_BTE11128XY2695_swatch.jpg?1649429551=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245311/original/TIE_NECKTIE_BTE11128XY2695_40_category-outfitter.jpg?1649686786=",
          color_presentation: "Yellow Blue Stripe",
        },
        {
          on_sale: true,
          markdown: true,
          inventory: 21,
          color_name: "navy micro dots",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 59,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/247162/original/TIE_NECKTIE_BTE11128XB2708_swatch.jpg?1651160593=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/247748/original/TIE_NECKTIE_BTE11128XB2708_40_category-outfitter.jpg?1651676498=",
          color_presentation: "Navy Micro Dots",
        },
        {
          on_sale: true,
          markdown: true,
          inventory: 92,
          color_name: "navy red dots",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 49,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/247164/original/TIE_NECKTIE_BTE11128XR2717_swatch.jpg?1651160622=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/247750/original/TIE_NECKTIE_BTE11128XR2717_40_category-outfitter.jpg?1651676505=",
          color_presentation: "Navy Red Dots",
        },
      ],
      number_of_swatches: 22,
      final_sale_swatches: [],
      full_price_swatches: [
        {
          on_sale: false,
          markdown: false,
          inventory: 106,
          color_name: "glen plaid - pumpkin spice",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 79,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/259475/original/TIE_NECKTIE_BTE11128XO3308_swatch.jpg?1660071624=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/264471/original/TIE_NECKTIE_BTE11128XO3308_40_outfitter.jpg?1661351204=",
          color_presentation: "Glen Plaid Pumpkin Spice",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 369,
          color_name: "navy",
          final_sale: false,
          full_price: 89,
          purchasable: true,
          current_price: 89,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/247176/original/TIE_NECKTIE_16735-BLK02_swatch.jpg?1651161471=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/247177/original/TIE_NECKTIE_16735-BLK02_40_category-outfitter.jpg?1651161589=",
          color_presentation: "Navy",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 315,
          color_name: "matte black",
          final_sale: false,
          full_price: 89,
          purchasable: true,
          current_price: 89,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/82229/original/Ties_Tie_21248-BK524_swatch.jpg?1541104693=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232995/original/TIE_NECKTIE_21248-BK524_40_category-outfitter.jpg?1637363791=",
          color_presentation: "Matte Black",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 14,
          color_name: "navy teal floral",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 79,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245109/original/TIE_NECKTIE_BTE11128XN2694_swatch.jpg?1649429039=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/245299/original/TIE_NECKTIE_BTE11128XN2694_40_category-outfitter.jpg?1649686714=",
          color_presentation: "Navy Teal Floral",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 129,
          color_name: "floral charm",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 79,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/259471/original/TIE_NECKTIE_BTE11128XB3306_swatch.jpg?1660071301=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/264234/original/TIE_NECKTIE_BTE11128XB3306_40_outfitter.jpg?1660849965=",
          color_presentation: "Floral Charm",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 131,
          color_name: "dot - cordal",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 79,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/259567/original/TIE_NECKTIE_BTE11128XR3309_swatch.jpg?1660140720=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/264240/original/TIE_NECKTIE_BTE11128XR3309_40_outfitter.jpg?1660849986=",
          color_presentation: "Dot Cordal",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 73,
          color_name: "thorpe hill - green",
          final_sale: false,
          full_price: 79,
          purchasable: true,
          current_price: 79,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/259461/original/TIE_NECKTIE_BTE11128XG3301_swatch.jpg?1660070775=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/264224/original/TIE_NECKTIE_BTE11128XG3301_40_outfitter.jpg?1660849930=",
          color_presentation: "Thorpe Hill Green",
        },
      ],
      number_of_markdown_swatches: 6,
      number_of_full_price_swatches: 16,
      number_of_final_sale_swatches: 0,
      variation_id: "BTE11128XO3308OS",
    },
    value: "Premium Necktie",
    is_slotted: false,
    labels: {},
  },
  {
    matched_terms: [],
    data: {
      id: "ACCES236-black snails",
      url: "cotton-blend-dress-socks",
      stores: ["Bonobos"],
      swatches: [
        {
          on_sale: false,
          markdown: false,
          inventory: 494,
          color_name: "black snails",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/265164/original/SOCK_DRESS-SOCK_BSC11186NB3045_swatch.jpg?1661451449=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/267348/original/SOCK_DRESS-SOCK_BSC11186NB3045_40_outfitter.jpg?1662749051=",
          color_presentation: "Black Snails",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 873,
          color_name: "black stripe",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232849/original/SOCK_OTHER-SOCK_BAC04568XBK669_90_hover.jpeg?1636657877=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/152479/original/SOCK_DRESS-SOCK_22847-BK669_swatch.jpg?1572383429=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227269/original/SOCK_OTHER-SOCK_BAC04568XBK669_1_category-outfitter.jpg?1634305062=",
          color_presentation: "Black Stripe",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 116,
          color_name: "charcoal pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232847/original/SOCK_DRESS-SOCK_BAC04569XBK594_90_hover.jpeg?1636657807=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129460/original/Mens-Accessories_Socks_22847-BK594_swatch.jpg?1556664395=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227271/original/SOCK_DRESS-SOCK_BAC04569XBK594_1_category-outfitter.jpg?1634305070=",
          color_presentation: "Charcoal Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 1573,
          color_name: "navy pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/231893/original/SOCK_DRESS-SOCK_BAC04569XMVA44_90_hover.jpeg?1636059902=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75426/original/Accessories_Socks_22847-MVA44_swatch.jpg?1535578351=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227279/original/SOCK_DRESS-SOCK_BAC04569XMVA44_1_category-outfitter.jpg?1634305099=",
          color_presentation: "Navy Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 243,
          color_name: "navy",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232853/original/SOCK_DRESS-SOCK_BAC04569XBNB95_90_hover.jpeg?1636658048=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75424/original/Accessories_Socks_22847-BNB95_swatch.jpg?1535578148=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227275/original/SOCK_DRESS-SOCK_BAC04569XBNB95_1_category-outfitter.jpg?1634305084=",
          color_presentation: "Navy",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 516,
          color_name: "black",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230973/original/SOCK_DRESS-SOCK_BAC04569XBK529_90_hover.jpg?1635979525=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75420/original/Accessories_Socks_22847-BK529_swatch.jpg?1535578047=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230972/original/SOCK_DRESS-SOCK_BAC04569XBK529_40_category-outfitter.jpg?1635979522=",
          color_presentation: "Black",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 433,
          color_name: "black pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232848/original/SOCK_DRESS-SOCK_BAC04569XBK595_90_hover.jpeg?1636657840=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129472/original/Mens-Accessories_Socks_22847-BK595_swatch.jpg?1556664565=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227273/original/SOCK_DRESS-SOCK_BAC04569XBK595_1_category-outfitter.jpg?1634305077=",
          color_presentation: "Black Pin Dot",
        },
      ],
      is_bundle: false,
      image_url:
        "https://bonobos-prod-s3.imgix.net/products/267348/original/SOCK_DRESS-SOCK_BSC11186NB3045_40_outfitter.jpg?1662749051=",
      color_name: "black snails",
      full_price: 15,
      final_sale: false,
      description: "Lightweight. Cushioned. Ventilated.",
      is_gift_card: false,
      is_new_color: true,
      current_price: 15,
      number_of_fits: 0,
      is_new_program: false,
      markdown_swatches: [],
      number_of_swatches: 16,
      final_sale_swatches: [
        {
          on_sale: true,
          markdown: false,
          inventory: 1,
          color_name: "light blue geo",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "Only a few left",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237700/original/SOCK_DRESS-SOCK_BSC10765NB2105_90_hover.jpg?1644248857=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237775/original/SOCK_DRESS-SOCK_BSC10765NB2105_swatch.jpg?1644254342=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237699/original/SOCK_DRESS-SOCK_BSC10765NB2105_40_outfitter.jpg?1644248855=",
          color_presentation: "Light Blue Geo",
        },
        {
          on_sale: true,
          markdown: false,
          inventory: 6,
          color_name: "tapestry blue dot",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237691/original/SOCK_DRESS-SOCK_BSC10765NB2106_90_hover.jpg?1644248832=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237769/original/SOCK_DRESS-SOCK_BSC10765NB2106_swatch.jpg?1644250222=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237690/original/SOCK_DRESS-SOCK_BSC10765NB2106_40_outfitter.jpg?1644248830=",
          color_presentation: "Tapestry Blue Dot",
        },
      ],
      full_price_swatches: [
        {
          on_sale: false,
          markdown: false,
          inventory: 494,
          color_name: "black snails",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/265164/original/SOCK_DRESS-SOCK_BSC11186NB3045_swatch.jpg?1661451449=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/267348/original/SOCK_DRESS-SOCK_BSC11186NB3045_40_outfitter.jpg?1662749051=",
          color_presentation: "Black Snails",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 873,
          color_name: "black stripe",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232849/original/SOCK_OTHER-SOCK_BAC04568XBK669_90_hover.jpeg?1636657877=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/152479/original/SOCK_DRESS-SOCK_22847-BK669_swatch.jpg?1572383429=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227269/original/SOCK_OTHER-SOCK_BAC04568XBK669_1_category-outfitter.jpg?1634305062=",
          color_presentation: "Black Stripe",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 116,
          color_name: "charcoal pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232847/original/SOCK_DRESS-SOCK_BAC04569XBK594_90_hover.jpeg?1636657807=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129460/original/Mens-Accessories_Socks_22847-BK594_swatch.jpg?1556664395=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227271/original/SOCK_DRESS-SOCK_BAC04569XBK594_1_category-outfitter.jpg?1634305070=",
          color_presentation: "Charcoal Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 1573,
          color_name: "navy pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/231893/original/SOCK_DRESS-SOCK_BAC04569XMVA44_90_hover.jpeg?1636059902=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75426/original/Accessories_Socks_22847-MVA44_swatch.jpg?1535578351=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227279/original/SOCK_DRESS-SOCK_BAC04569XMVA44_1_category-outfitter.jpg?1634305099=",
          color_presentation: "Navy Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 243,
          color_name: "navy",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232853/original/SOCK_DRESS-SOCK_BAC04569XBNB95_90_hover.jpeg?1636658048=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75424/original/Accessories_Socks_22847-BNB95_swatch.jpg?1535578148=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227275/original/SOCK_DRESS-SOCK_BAC04569XBNB95_1_category-outfitter.jpg?1634305084=",
          color_presentation: "Navy",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 516,
          color_name: "black",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230973/original/SOCK_DRESS-SOCK_BAC04569XBK529_90_hover.jpg?1635979525=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75420/original/Accessories_Socks_22847-BK529_swatch.jpg?1535578047=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230972/original/SOCK_DRESS-SOCK_BAC04569XBK529_40_category-outfitter.jpg?1635979522=",
          color_presentation: "Black",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 433,
          color_name: "black pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232848/original/SOCK_DRESS-SOCK_BAC04569XBK595_90_hover.jpeg?1636657840=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129472/original/Mens-Accessories_Socks_22847-BK595_swatch.jpg?1556664565=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227273/original/SOCK_DRESS-SOCK_BAC04569XBK595_1_category-outfitter.jpg?1634305077=",
          color_presentation: "Black Pin Dot",
        },
      ],
      number_of_markdown_swatches: 0,
      number_of_full_price_swatches: 14,
      number_of_final_sale_swatches: 2,
      variation_id: "BSC11186NB3045ML",
    },
    value: "Soft Everyday Socks",
    is_slotted: false,
    labels: {},
  },
  {
    matched_terms: [],
    data: {
      id: "ACCES00267-navy stripe",
      url: "extrasoft-socks",
      stores: ["Bonobos"],
      swatches: [
        {
          on_sale: false,
          markdown: false,
          inventory: 297,
          color_name: "navy stripe",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/265174/original/SOCK_OTHER-SOCK_BSC11188NN3047_swatch.jpg?1661452021=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/267372/original/SOCK_OTHER-SOCK_BSC11188NN3047_40_outfitter.jpg?1662749061=",
          color_presentation: "Navy Stripe",
        },
        {
          on_sale: true,
          markdown: false,
          inventory: 132,
          color_name: "blue pineapples",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237703/original/SOCK_OTHER-SOCK_BSC11023NB2103_90_hover.jpg?1644248865=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237777/original/SOCK_OTHER-SOCK_BSC11023NB2103_swatch.jpg?1644254391=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237702/original/SOCK_OTHER-SOCK_BSC11023NB2103_40_outfitter.jpg?1644248863=",
          color_presentation: "Blue Pineapples",
        },
        {
          on_sale: true,
          markdown: false,
          inventory: 245,
          color_name: "blue boats",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237706/original/SOCK_OTHER-SOCK_BSC11023NB2102_90_hover.jpg?1644248874=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237779/original/SOCK_OTHER-SOCK_BSC11023NB2102_swatch.jpg?1644254419=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237705/original/SOCK_OTHER-SOCK_BSC11023NB2102_40_outfitter.jpg?1644248872=",
          color_presentation: "Blue Boats",
        },
        {
          on_sale: true,
          markdown: false,
          inventory: 207,
          color_name: "grey plant",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237709/original/SOCK_OTHER-SOCK_BSC11023NG2101_90_hover.jpg?1644248882=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237781/original/SOCK_OTHER-SOCK_BSC11023NG2101_swatch.jpg?1644254450=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237708/original/SOCK_OTHER-SOCK_BSC11023NG2101_40_outfitter.jpg?1644248880=",
          color_presentation: "Grey Plant",
        },
      ],
      is_bundle: false,
      image_url:
        "https://bonobos-prod-s3.imgix.net/products/267372/original/SOCK_OTHER-SOCK_BSC11188NN3047_40_outfitter.jpg?1662749061=",
      color_name: "navy stripe",
      full_price: 15,
      final_sale: false,
      description:
        "Don't overlook your socks. You deserve all-day softness that helps you feel great from the ground up.",
      is_gift_card: false,
      is_new_color: true,
      current_price: 15,
      number_of_fits: 0,
      is_new_program: false,
      markdown_swatches: [],
      number_of_swatches: 4,
      final_sale_swatches: [
        {
          on_sale: true,
          markdown: false,
          inventory: 132,
          color_name: "blue pineapples",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237703/original/SOCK_OTHER-SOCK_BSC11023NB2103_90_hover.jpg?1644248865=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237777/original/SOCK_OTHER-SOCK_BSC11023NB2103_swatch.jpg?1644254391=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237702/original/SOCK_OTHER-SOCK_BSC11023NB2103_40_outfitter.jpg?1644248863=",
          color_presentation: "Blue Pineapples",
        },
        {
          on_sale: true,
          markdown: false,
          inventory: 245,
          color_name: "blue boats",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237706/original/SOCK_OTHER-SOCK_BSC11023NB2102_90_hover.jpg?1644248874=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237779/original/SOCK_OTHER-SOCK_BSC11023NB2102_swatch.jpg?1644254419=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237705/original/SOCK_OTHER-SOCK_BSC11023NB2102_40_outfitter.jpg?1644248872=",
          color_presentation: "Blue Boats",
        },
        {
          on_sale: true,
          markdown: false,
          inventory: 207,
          color_name: "grey plant",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237709/original/SOCK_OTHER-SOCK_BSC11023NG2101_90_hover.jpg?1644248882=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237781/original/SOCK_OTHER-SOCK_BSC11023NG2101_swatch.jpg?1644254450=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237708/original/SOCK_OTHER-SOCK_BSC11023NG2101_40_outfitter.jpg?1644248880=",
          color_presentation: "Grey Plant",
        },
      ],
      full_price_swatches: [
        {
          on_sale: false,
          markdown: false,
          inventory: 297,
          color_name: "navy stripe",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/265174/original/SOCK_OTHER-SOCK_BSC11188NN3047_swatch.jpg?1661452021=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/267372/original/SOCK_OTHER-SOCK_BSC11188NN3047_40_outfitter.jpg?1662749061=",
          color_presentation: "Navy Stripe",
        },
      ],
      number_of_markdown_swatches: 0,
      number_of_full_price_swatches: 1,
      number_of_final_sale_swatches: 3,
      variation_id: "BSC11188NN3047ML",
    },
    value: "Extrasoft Socks",
    is_slotted: false,
    labels: {},
  },
  {
    matched_terms: [],
    data: {
      id: "ACCES236-burgundy dot",
      url: "cotton-blend-dress-socks",
      stores: ["Bonobos"],
      swatches: [
        {
          on_sale: false,
          markdown: false,
          inventory: 277,
          color_name: "burgundy dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/265172/original/SOCK_DRESS-SOCK_BSC11186NR3048_swatch.jpg?1661451888=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/267308/original/SOCK_DRESS-SOCK_BSC11186NR3048_40_outfitter.jpg?1662749034=",
          color_presentation: "Burgundy Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 873,
          color_name: "black stripe",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232849/original/SOCK_OTHER-SOCK_BAC04568XBK669_90_hover.jpeg?1636657877=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/152479/original/SOCK_DRESS-SOCK_22847-BK669_swatch.jpg?1572383429=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227269/original/SOCK_OTHER-SOCK_BAC04568XBK669_1_category-outfitter.jpg?1634305062=",
          color_presentation: "Black Stripe",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 116,
          color_name: "charcoal pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232847/original/SOCK_DRESS-SOCK_BAC04569XBK594_90_hover.jpeg?1636657807=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129460/original/Mens-Accessories_Socks_22847-BK594_swatch.jpg?1556664395=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227271/original/SOCK_DRESS-SOCK_BAC04569XBK594_1_category-outfitter.jpg?1634305070=",
          color_presentation: "Charcoal Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 1573,
          color_name: "navy pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/231893/original/SOCK_DRESS-SOCK_BAC04569XMVA44_90_hover.jpeg?1636059902=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75426/original/Accessories_Socks_22847-MVA44_swatch.jpg?1535578351=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227279/original/SOCK_DRESS-SOCK_BAC04569XMVA44_1_category-outfitter.jpg?1634305099=",
          color_presentation: "Navy Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 243,
          color_name: "navy",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232853/original/SOCK_DRESS-SOCK_BAC04569XBNB95_90_hover.jpeg?1636658048=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75424/original/Accessories_Socks_22847-BNB95_swatch.jpg?1535578148=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227275/original/SOCK_DRESS-SOCK_BAC04569XBNB95_1_category-outfitter.jpg?1634305084=",
          color_presentation: "Navy",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 516,
          color_name: "black",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230973/original/SOCK_DRESS-SOCK_BAC04569XBK529_90_hover.jpg?1635979525=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75420/original/Accessories_Socks_22847-BK529_swatch.jpg?1535578047=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230972/original/SOCK_DRESS-SOCK_BAC04569XBK529_40_category-outfitter.jpg?1635979522=",
          color_presentation: "Black",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 433,
          color_name: "black pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232848/original/SOCK_DRESS-SOCK_BAC04569XBK595_90_hover.jpeg?1636657840=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129472/original/Mens-Accessories_Socks_22847-BK595_swatch.jpg?1556664565=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227273/original/SOCK_DRESS-SOCK_BAC04569XBK595_1_category-outfitter.jpg?1634305077=",
          color_presentation: "Black Pin Dot",
        },
      ],
      is_bundle: false,
      image_url:
        "https://bonobos-prod-s3.imgix.net/products/267308/original/SOCK_DRESS-SOCK_BSC11186NR3048_40_outfitter.jpg?1662749034=",
      color_name: "burgundy dot",
      full_price: 15,
      final_sale: false,
      description: "Lightweight. Cushioned. Ventilated.",
      is_gift_card: false,
      is_new_color: true,
      current_price: 15,
      number_of_fits: 0,
      is_new_program: false,
      markdown_swatches: [],
      number_of_swatches: 16,
      final_sale_swatches: [
        {
          on_sale: true,
          markdown: false,
          inventory: 1,
          color_name: "light blue geo",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "Only a few left",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237700/original/SOCK_DRESS-SOCK_BSC10765NB2105_90_hover.jpg?1644248857=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237775/original/SOCK_DRESS-SOCK_BSC10765NB2105_swatch.jpg?1644254342=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237699/original/SOCK_DRESS-SOCK_BSC10765NB2105_40_outfitter.jpg?1644248855=",
          color_presentation: "Light Blue Geo",
        },
        {
          on_sale: true,
          markdown: false,
          inventory: 6,
          color_name: "tapestry blue dot",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237691/original/SOCK_DRESS-SOCK_BSC10765NB2106_90_hover.jpg?1644248832=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237769/original/SOCK_DRESS-SOCK_BSC10765NB2106_swatch.jpg?1644250222=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237690/original/SOCK_DRESS-SOCK_BSC10765NB2106_40_outfitter.jpg?1644248830=",
          color_presentation: "Tapestry Blue Dot",
        },
      ],
      full_price_swatches: [
        {
          on_sale: false,
          markdown: false,
          inventory: 277,
          color_name: "burgundy dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/265172/original/SOCK_DRESS-SOCK_BSC11186NR3048_swatch.jpg?1661451888=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/267308/original/SOCK_DRESS-SOCK_BSC11186NR3048_40_outfitter.jpg?1662749034=",
          color_presentation: "Burgundy Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 873,
          color_name: "black stripe",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232849/original/SOCK_OTHER-SOCK_BAC04568XBK669_90_hover.jpeg?1636657877=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/152479/original/SOCK_DRESS-SOCK_22847-BK669_swatch.jpg?1572383429=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227269/original/SOCK_OTHER-SOCK_BAC04568XBK669_1_category-outfitter.jpg?1634305062=",
          color_presentation: "Black Stripe",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 116,
          color_name: "charcoal pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232847/original/SOCK_DRESS-SOCK_BAC04569XBK594_90_hover.jpeg?1636657807=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129460/original/Mens-Accessories_Socks_22847-BK594_swatch.jpg?1556664395=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227271/original/SOCK_DRESS-SOCK_BAC04569XBK594_1_category-outfitter.jpg?1634305070=",
          color_presentation: "Charcoal Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 1573,
          color_name: "navy pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/231893/original/SOCK_DRESS-SOCK_BAC04569XMVA44_90_hover.jpeg?1636059902=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75426/original/Accessories_Socks_22847-MVA44_swatch.jpg?1535578351=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227279/original/SOCK_DRESS-SOCK_BAC04569XMVA44_1_category-outfitter.jpg?1634305099=",
          color_presentation: "Navy Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 243,
          color_name: "navy",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232853/original/SOCK_DRESS-SOCK_BAC04569XBNB95_90_hover.jpeg?1636658048=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75424/original/Accessories_Socks_22847-BNB95_swatch.jpg?1535578148=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227275/original/SOCK_DRESS-SOCK_BAC04569XBNB95_1_category-outfitter.jpg?1634305084=",
          color_presentation: "Navy",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 516,
          color_name: "black",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230973/original/SOCK_DRESS-SOCK_BAC04569XBK529_90_hover.jpg?1635979525=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75420/original/Accessories_Socks_22847-BK529_swatch.jpg?1535578047=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230972/original/SOCK_DRESS-SOCK_BAC04569XBK529_40_category-outfitter.jpg?1635979522=",
          color_presentation: "Black",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 433,
          color_name: "black pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232848/original/SOCK_DRESS-SOCK_BAC04569XBK595_90_hover.jpeg?1636657840=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129472/original/Mens-Accessories_Socks_22847-BK595_swatch.jpg?1556664565=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227273/original/SOCK_DRESS-SOCK_BAC04569XBK595_1_category-outfitter.jpg?1634305077=",
          color_presentation: "Black Pin Dot",
        },
      ],
      number_of_markdown_swatches: 0,
      number_of_full_price_swatches: 14,
      number_of_final_sale_swatches: 2,
      variation_id: "BSC11186NR3048ML",
    },
    value: "Soft Everyday Socks",
    is_slotted: false,
    labels: {},
  },
  {
    matched_terms: [],
    data: {
      id: "ACCES236-blue pizza",
      url: "cotton-blend-dress-socks",
      stores: ["Bonobos"],
      swatches: [
        {
          on_sale: false,
          markdown: false,
          inventory: 343,
          color_name: "blue pizza",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/265168/original/SOCK_DRESS-SOCK_BSC11186NN3043_swatch.jpg?1661451643=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/267288/original/SOCK_DRESS-SOCK_BSC11186NN3043_40_outfitter.jpg?1662749027=",
          color_presentation: "Blue Pizza",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 873,
          color_name: "black stripe",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232849/original/SOCK_OTHER-SOCK_BAC04568XBK669_90_hover.jpeg?1636657877=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/152479/original/SOCK_DRESS-SOCK_22847-BK669_swatch.jpg?1572383429=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227269/original/SOCK_OTHER-SOCK_BAC04568XBK669_1_category-outfitter.jpg?1634305062=",
          color_presentation: "Black Stripe",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 116,
          color_name: "charcoal pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232847/original/SOCK_DRESS-SOCK_BAC04569XBK594_90_hover.jpeg?1636657807=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129460/original/Mens-Accessories_Socks_22847-BK594_swatch.jpg?1556664395=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227271/original/SOCK_DRESS-SOCK_BAC04569XBK594_1_category-outfitter.jpg?1634305070=",
          color_presentation: "Charcoal Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 1573,
          color_name: "navy pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/231893/original/SOCK_DRESS-SOCK_BAC04569XMVA44_90_hover.jpeg?1636059902=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75426/original/Accessories_Socks_22847-MVA44_swatch.jpg?1535578351=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227279/original/SOCK_DRESS-SOCK_BAC04569XMVA44_1_category-outfitter.jpg?1634305099=",
          color_presentation: "Navy Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 243,
          color_name: "navy",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232853/original/SOCK_DRESS-SOCK_BAC04569XBNB95_90_hover.jpeg?1636658048=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75424/original/Accessories_Socks_22847-BNB95_swatch.jpg?1535578148=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227275/original/SOCK_DRESS-SOCK_BAC04569XBNB95_1_category-outfitter.jpg?1634305084=",
          color_presentation: "Navy",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 516,
          color_name: "black",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230973/original/SOCK_DRESS-SOCK_BAC04569XBK529_90_hover.jpg?1635979525=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75420/original/Accessories_Socks_22847-BK529_swatch.jpg?1535578047=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230972/original/SOCK_DRESS-SOCK_BAC04569XBK529_40_category-outfitter.jpg?1635979522=",
          color_presentation: "Black",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 433,
          color_name: "black pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232848/original/SOCK_DRESS-SOCK_BAC04569XBK595_90_hover.jpeg?1636657840=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129472/original/Mens-Accessories_Socks_22847-BK595_swatch.jpg?1556664565=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227273/original/SOCK_DRESS-SOCK_BAC04569XBK595_1_category-outfitter.jpg?1634305077=",
          color_presentation: "Black Pin Dot",
        },
      ],
      is_bundle: false,
      image_url:
        "https://bonobos-prod-s3.imgix.net/products/267288/original/SOCK_DRESS-SOCK_BSC11186NN3043_40_outfitter.jpg?1662749027=",
      color_name: "blue pizza",
      full_price: 15,
      final_sale: false,
      description: "Lightweight. Cushioned. Ventilated.",
      is_gift_card: false,
      is_new_color: true,
      current_price: 15,
      number_of_fits: 0,
      is_new_program: false,
      markdown_swatches: [],
      number_of_swatches: 16,
      final_sale_swatches: [
        {
          on_sale: true,
          markdown: false,
          inventory: 1,
          color_name: "light blue geo",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "Only a few left",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237700/original/SOCK_DRESS-SOCK_BSC10765NB2105_90_hover.jpg?1644248857=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237775/original/SOCK_DRESS-SOCK_BSC10765NB2105_swatch.jpg?1644254342=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237699/original/SOCK_DRESS-SOCK_BSC10765NB2105_40_outfitter.jpg?1644248855=",
          color_presentation: "Light Blue Geo",
        },
        {
          on_sale: true,
          markdown: false,
          inventory: 6,
          color_name: "tapestry blue dot",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237691/original/SOCK_DRESS-SOCK_BSC10765NB2106_90_hover.jpg?1644248832=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237769/original/SOCK_DRESS-SOCK_BSC10765NB2106_swatch.jpg?1644250222=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237690/original/SOCK_DRESS-SOCK_BSC10765NB2106_40_outfitter.jpg?1644248830=",
          color_presentation: "Tapestry Blue Dot",
        },
      ],
      full_price_swatches: [
        {
          on_sale: false,
          markdown: false,
          inventory: 343,
          color_name: "blue pizza",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/265168/original/SOCK_DRESS-SOCK_BSC11186NN3043_swatch.jpg?1661451643=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/267288/original/SOCK_DRESS-SOCK_BSC11186NN3043_40_outfitter.jpg?1662749027=",
          color_presentation: "Blue Pizza",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 873,
          color_name: "black stripe",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232849/original/SOCK_OTHER-SOCK_BAC04568XBK669_90_hover.jpeg?1636657877=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/152479/original/SOCK_DRESS-SOCK_22847-BK669_swatch.jpg?1572383429=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227269/original/SOCK_OTHER-SOCK_BAC04568XBK669_1_category-outfitter.jpg?1634305062=",
          color_presentation: "Black Stripe",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 116,
          color_name: "charcoal pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232847/original/SOCK_DRESS-SOCK_BAC04569XBK594_90_hover.jpeg?1636657807=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129460/original/Mens-Accessories_Socks_22847-BK594_swatch.jpg?1556664395=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227271/original/SOCK_DRESS-SOCK_BAC04569XBK594_1_category-outfitter.jpg?1634305070=",
          color_presentation: "Charcoal Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 1573,
          color_name: "navy pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/231893/original/SOCK_DRESS-SOCK_BAC04569XMVA44_90_hover.jpeg?1636059902=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75426/original/Accessories_Socks_22847-MVA44_swatch.jpg?1535578351=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227279/original/SOCK_DRESS-SOCK_BAC04569XMVA44_1_category-outfitter.jpg?1634305099=",
          color_presentation: "Navy Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 243,
          color_name: "navy",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232853/original/SOCK_DRESS-SOCK_BAC04569XBNB95_90_hover.jpeg?1636658048=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75424/original/Accessories_Socks_22847-BNB95_swatch.jpg?1535578148=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227275/original/SOCK_DRESS-SOCK_BAC04569XBNB95_1_category-outfitter.jpg?1634305084=",
          color_presentation: "Navy",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 516,
          color_name: "black",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230973/original/SOCK_DRESS-SOCK_BAC04569XBK529_90_hover.jpg?1635979525=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75420/original/Accessories_Socks_22847-BK529_swatch.jpg?1535578047=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230972/original/SOCK_DRESS-SOCK_BAC04569XBK529_40_category-outfitter.jpg?1635979522=",
          color_presentation: "Black",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 433,
          color_name: "black pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232848/original/SOCK_DRESS-SOCK_BAC04569XBK595_90_hover.jpeg?1636657840=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129472/original/Mens-Accessories_Socks_22847-BK595_swatch.jpg?1556664565=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227273/original/SOCK_DRESS-SOCK_BAC04569XBK595_1_category-outfitter.jpg?1634305077=",
          color_presentation: "Black Pin Dot",
        },
      ],
      number_of_markdown_swatches: 0,
      number_of_full_price_swatches: 14,
      number_of_final_sale_swatches: 2,
      variation_id: "BSC11186NN3043ML",
    },
    value: "Soft Everyday Socks",
    is_slotted: false,
    labels: {},
  },
  {
    matched_terms: [],
    data: {
      id: "ACCES236-blue drinks",
      url: "cotton-blend-dress-socks",
      stores: ["Bonobos"],
      swatches: [
        {
          on_sale: false,
          markdown: false,
          inventory: 164,
          color_name: "blue drinks",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/265170/original/SOCK_DRESS-SOCK_BSC11186NB3049_swatch.jpg?1661451762=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/267272/original/SOCK_DRESS-SOCK_BSC11186NB3049_40_outfitter.jpg?1662749020=",
          color_presentation: "Blue Drinks",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 873,
          color_name: "black stripe",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232849/original/SOCK_OTHER-SOCK_BAC04568XBK669_90_hover.jpeg?1636657877=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/152479/original/SOCK_DRESS-SOCK_22847-BK669_swatch.jpg?1572383429=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227269/original/SOCK_OTHER-SOCK_BAC04568XBK669_1_category-outfitter.jpg?1634305062=",
          color_presentation: "Black Stripe",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 116,
          color_name: "charcoal pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232847/original/SOCK_DRESS-SOCK_BAC04569XBK594_90_hover.jpeg?1636657807=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129460/original/Mens-Accessories_Socks_22847-BK594_swatch.jpg?1556664395=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227271/original/SOCK_DRESS-SOCK_BAC04569XBK594_1_category-outfitter.jpg?1634305070=",
          color_presentation: "Charcoal Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 1573,
          color_name: "navy pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/231893/original/SOCK_DRESS-SOCK_BAC04569XMVA44_90_hover.jpeg?1636059902=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75426/original/Accessories_Socks_22847-MVA44_swatch.jpg?1535578351=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227279/original/SOCK_DRESS-SOCK_BAC04569XMVA44_1_category-outfitter.jpg?1634305099=",
          color_presentation: "Navy Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 243,
          color_name: "navy",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232853/original/SOCK_DRESS-SOCK_BAC04569XBNB95_90_hover.jpeg?1636658048=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75424/original/Accessories_Socks_22847-BNB95_swatch.jpg?1535578148=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227275/original/SOCK_DRESS-SOCK_BAC04569XBNB95_1_category-outfitter.jpg?1634305084=",
          color_presentation: "Navy",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 516,
          color_name: "black",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230973/original/SOCK_DRESS-SOCK_BAC04569XBK529_90_hover.jpg?1635979525=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75420/original/Accessories_Socks_22847-BK529_swatch.jpg?1535578047=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230972/original/SOCK_DRESS-SOCK_BAC04569XBK529_40_category-outfitter.jpg?1635979522=",
          color_presentation: "Black",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 433,
          color_name: "black pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232848/original/SOCK_DRESS-SOCK_BAC04569XBK595_90_hover.jpeg?1636657840=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129472/original/Mens-Accessories_Socks_22847-BK595_swatch.jpg?1556664565=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227273/original/SOCK_DRESS-SOCK_BAC04569XBK595_1_category-outfitter.jpg?1634305077=",
          color_presentation: "Black Pin Dot",
        },
      ],
      is_bundle: false,
      image_url:
        "https://bonobos-prod-s3.imgix.net/products/267272/original/SOCK_DRESS-SOCK_BSC11186NB3049_40_outfitter.jpg?1662749020=",
      color_name: "blue drinks",
      full_price: 15,
      final_sale: false,
      description: "Lightweight. Cushioned. Ventilated.",
      is_gift_card: false,
      is_new_color: true,
      current_price: 15,
      number_of_fits: 0,
      is_new_program: false,
      markdown_swatches: [],
      number_of_swatches: 16,
      final_sale_swatches: [
        {
          on_sale: true,
          markdown: false,
          inventory: 1,
          color_name: "light blue geo",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "Only a few left",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237700/original/SOCK_DRESS-SOCK_BSC10765NB2105_90_hover.jpg?1644248857=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237775/original/SOCK_DRESS-SOCK_BSC10765NB2105_swatch.jpg?1644254342=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237699/original/SOCK_DRESS-SOCK_BSC10765NB2105_40_outfitter.jpg?1644248855=",
          color_presentation: "Light Blue Geo",
        },
        {
          on_sale: true,
          markdown: false,
          inventory: 6,
          color_name: "tapestry blue dot",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237691/original/SOCK_DRESS-SOCK_BSC10765NB2106_90_hover.jpg?1644248832=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237769/original/SOCK_DRESS-SOCK_BSC10765NB2106_swatch.jpg?1644250222=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237690/original/SOCK_DRESS-SOCK_BSC10765NB2106_40_outfitter.jpg?1644248830=",
          color_presentation: "Tapestry Blue Dot",
        },
      ],
      full_price_swatches: [
        {
          on_sale: false,
          markdown: false,
          inventory: 164,
          color_name: "blue drinks",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/265170/original/SOCK_DRESS-SOCK_BSC11186NB3049_swatch.jpg?1661451762=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/267272/original/SOCK_DRESS-SOCK_BSC11186NB3049_40_outfitter.jpg?1662749020=",
          color_presentation: "Blue Drinks",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 873,
          color_name: "black stripe",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232849/original/SOCK_OTHER-SOCK_BAC04568XBK669_90_hover.jpeg?1636657877=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/152479/original/SOCK_DRESS-SOCK_22847-BK669_swatch.jpg?1572383429=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227269/original/SOCK_OTHER-SOCK_BAC04568XBK669_1_category-outfitter.jpg?1634305062=",
          color_presentation: "Black Stripe",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 116,
          color_name: "charcoal pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232847/original/SOCK_DRESS-SOCK_BAC04569XBK594_90_hover.jpeg?1636657807=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129460/original/Mens-Accessories_Socks_22847-BK594_swatch.jpg?1556664395=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227271/original/SOCK_DRESS-SOCK_BAC04569XBK594_1_category-outfitter.jpg?1634305070=",
          color_presentation: "Charcoal Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 1573,
          color_name: "navy pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/231893/original/SOCK_DRESS-SOCK_BAC04569XMVA44_90_hover.jpeg?1636059902=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75426/original/Accessories_Socks_22847-MVA44_swatch.jpg?1535578351=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227279/original/SOCK_DRESS-SOCK_BAC04569XMVA44_1_category-outfitter.jpg?1634305099=",
          color_presentation: "Navy Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 243,
          color_name: "navy",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232853/original/SOCK_DRESS-SOCK_BAC04569XBNB95_90_hover.jpeg?1636658048=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75424/original/Accessories_Socks_22847-BNB95_swatch.jpg?1535578148=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227275/original/SOCK_DRESS-SOCK_BAC04569XBNB95_1_category-outfitter.jpg?1634305084=",
          color_presentation: "Navy",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 516,
          color_name: "black",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230973/original/SOCK_DRESS-SOCK_BAC04569XBK529_90_hover.jpg?1635979525=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75420/original/Accessories_Socks_22847-BK529_swatch.jpg?1535578047=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230972/original/SOCK_DRESS-SOCK_BAC04569XBK529_40_category-outfitter.jpg?1635979522=",
          color_presentation: "Black",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 433,
          color_name: "black pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232848/original/SOCK_DRESS-SOCK_BAC04569XBK595_90_hover.jpeg?1636657840=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129472/original/Mens-Accessories_Socks_22847-BK595_swatch.jpg?1556664565=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227273/original/SOCK_DRESS-SOCK_BAC04569XBK595_1_category-outfitter.jpg?1634305077=",
          color_presentation: "Black Pin Dot",
        },
      ],
      number_of_markdown_swatches: 0,
      number_of_full_price_swatches: 14,
      number_of_final_sale_swatches: 2,
      variation_id: "BSC11186NB3049ML",
    },
    value: "Soft Everyday Socks",
    is_slotted: false,
    labels: {},
  },
  {
    matched_terms: [],
    data: {
      id: "ACCES236-mineral blue skunks",
      url: "cotton-blend-dress-socks",
      stores: ["Bonobos"],
      swatches: [
        {
          on_sale: false,
          markdown: false,
          inventory: 395,
          color_name: "mineral blue skunks",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/265166/original/SOCK_DRESS-SOCK_BSC11186NG3044_swatch.jpg?1661451587=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/267325/original/SOCK_DRESS-SOCK_BSC11186NG3044_40_outfitter.jpg?1662749040=",
          color_presentation: "Mineral Blue Skunks",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 873,
          color_name: "black stripe",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232849/original/SOCK_OTHER-SOCK_BAC04568XBK669_90_hover.jpeg?1636657877=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/152479/original/SOCK_DRESS-SOCK_22847-BK669_swatch.jpg?1572383429=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227269/original/SOCK_OTHER-SOCK_BAC04568XBK669_1_category-outfitter.jpg?1634305062=",
          color_presentation: "Black Stripe",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 116,
          color_name: "charcoal pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232847/original/SOCK_DRESS-SOCK_BAC04569XBK594_90_hover.jpeg?1636657807=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129460/original/Mens-Accessories_Socks_22847-BK594_swatch.jpg?1556664395=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227271/original/SOCK_DRESS-SOCK_BAC04569XBK594_1_category-outfitter.jpg?1634305070=",
          color_presentation: "Charcoal Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 1573,
          color_name: "navy pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/231893/original/SOCK_DRESS-SOCK_BAC04569XMVA44_90_hover.jpeg?1636059902=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75426/original/Accessories_Socks_22847-MVA44_swatch.jpg?1535578351=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227279/original/SOCK_DRESS-SOCK_BAC04569XMVA44_1_category-outfitter.jpg?1634305099=",
          color_presentation: "Navy Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 243,
          color_name: "navy",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232853/original/SOCK_DRESS-SOCK_BAC04569XBNB95_90_hover.jpeg?1636658048=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75424/original/Accessories_Socks_22847-BNB95_swatch.jpg?1535578148=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227275/original/SOCK_DRESS-SOCK_BAC04569XBNB95_1_category-outfitter.jpg?1634305084=",
          color_presentation: "Navy",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 516,
          color_name: "black",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230973/original/SOCK_DRESS-SOCK_BAC04569XBK529_90_hover.jpg?1635979525=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75420/original/Accessories_Socks_22847-BK529_swatch.jpg?1535578047=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230972/original/SOCK_DRESS-SOCK_BAC04569XBK529_40_category-outfitter.jpg?1635979522=",
          color_presentation: "Black",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 433,
          color_name: "black pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232848/original/SOCK_DRESS-SOCK_BAC04569XBK595_90_hover.jpeg?1636657840=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129472/original/Mens-Accessories_Socks_22847-BK595_swatch.jpg?1556664565=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227273/original/SOCK_DRESS-SOCK_BAC04569XBK595_1_category-outfitter.jpg?1634305077=",
          color_presentation: "Black Pin Dot",
        },
      ],
      is_bundle: false,
      image_url:
        "https://bonobos-prod-s3.imgix.net/products/267325/original/SOCK_DRESS-SOCK_BSC11186NG3044_40_outfitter.jpg?1662749040=",
      color_name: "mineral blue skunks",
      full_price: 15,
      final_sale: false,
      description: "Lightweight. Cushioned. Ventilated.",
      is_gift_card: false,
      is_new_color: true,
      current_price: 15,
      number_of_fits: 0,
      is_new_program: false,
      markdown_swatches: [],
      number_of_swatches: 16,
      final_sale_swatches: [
        {
          on_sale: true,
          markdown: false,
          inventory: 1,
          color_name: "light blue geo",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "Only a few left",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237700/original/SOCK_DRESS-SOCK_BSC10765NB2105_90_hover.jpg?1644248857=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237775/original/SOCK_DRESS-SOCK_BSC10765NB2105_swatch.jpg?1644254342=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237699/original/SOCK_DRESS-SOCK_BSC10765NB2105_40_outfitter.jpg?1644248855=",
          color_presentation: "Light Blue Geo",
        },
        {
          on_sale: true,
          markdown: false,
          inventory: 6,
          color_name: "tapestry blue dot",
          final_sale: true,
          full_price: 15,
          purchasable: true,
          current_price: 8,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237691/original/SOCK_DRESS-SOCK_BSC10765NB2106_90_hover.jpg?1644248832=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237769/original/SOCK_DRESS-SOCK_BSC10765NB2106_swatch.jpg?1644250222=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/237690/original/SOCK_DRESS-SOCK_BSC10765NB2106_40_outfitter.jpg?1644248830=",
          color_presentation: "Tapestry Blue Dot",
        },
      ],
      full_price_swatches: [
        {
          on_sale: false,
          markdown: false,
          inventory: 395,
          color_name: "mineral blue skunks",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url: null,
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/265166/original/SOCK_DRESS-SOCK_BSC11186NG3044_swatch.jpg?1661451587=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/267325/original/SOCK_DRESS-SOCK_BSC11186NG3044_40_outfitter.jpg?1662749040=",
          color_presentation: "Mineral Blue Skunks",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 873,
          color_name: "black stripe",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232849/original/SOCK_OTHER-SOCK_BAC04568XBK669_90_hover.jpeg?1636657877=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/152479/original/SOCK_DRESS-SOCK_22847-BK669_swatch.jpg?1572383429=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227269/original/SOCK_OTHER-SOCK_BAC04568XBK669_1_category-outfitter.jpg?1634305062=",
          color_presentation: "Black Stripe",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 116,
          color_name: "charcoal pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232847/original/SOCK_DRESS-SOCK_BAC04569XBK594_90_hover.jpeg?1636657807=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129460/original/Mens-Accessories_Socks_22847-BK594_swatch.jpg?1556664395=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227271/original/SOCK_DRESS-SOCK_BAC04569XBK594_1_category-outfitter.jpg?1634305070=",
          color_presentation: "Charcoal Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 1573,
          color_name: "navy pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/231893/original/SOCK_DRESS-SOCK_BAC04569XMVA44_90_hover.jpeg?1636059902=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75426/original/Accessories_Socks_22847-MVA44_swatch.jpg?1535578351=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227279/original/SOCK_DRESS-SOCK_BAC04569XMVA44_1_category-outfitter.jpg?1634305099=",
          color_presentation: "Navy Pin Dot",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 243,
          color_name: "navy",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232853/original/SOCK_DRESS-SOCK_BAC04569XBNB95_90_hover.jpeg?1636658048=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75424/original/Accessories_Socks_22847-BNB95_swatch.jpg?1535578148=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227275/original/SOCK_DRESS-SOCK_BAC04569XBNB95_1_category-outfitter.jpg?1634305084=",
          color_presentation: "Navy",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 516,
          color_name: "black",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230973/original/SOCK_DRESS-SOCK_BAC04569XBK529_90_hover.jpg?1635979525=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/75420/original/Accessories_Socks_22847-BK529_swatch.jpg?1535578047=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/230972/original/SOCK_DRESS-SOCK_BAC04569XBK529_40_category-outfitter.jpg?1635979522=",
          color_presentation: "Black",
        },
        {
          on_sale: false,
          markdown: false,
          inventory: 433,
          color_name: "black pin dot",
          final_sale: false,
          full_price: 15,
          purchasable: true,
          current_price: 15,
          novelty_badge: "",
          urgency_badge: "",
          hover_image_url:
            "https://bonobos-prod-s3.imgix.net/products/232848/original/SOCK_DRESS-SOCK_BAC04569XBK595_90_hover.jpeg?1636657840=",
          swatch_image_url:
            "https://bonobos-prod-s3.imgix.net/products/129472/original/Mens-Accessories_Socks_22847-BK595_swatch.jpg?1556664565=",
          primary_image_url:
            "https://bonobos-prod-s3.imgix.net/products/227273/original/SOCK_DRESS-SOCK_BAC04569XBK595_1_category-outfitter.jpg?1634305077=",
          color_presentation: "Black Pin Dot",
        },
      ],
      number_of_markdown_swatches: 0,
      number_of_full_price_swatches: 14,
      number_of_final_sale_swatches: 2,
      variation_id: "BSC11186NG3044ML",
    },
    value: "Soft Everyday Socks",
    is_slotted: false,
    labels: {},
  },
];
