export default [
  {
    id: "100",
    name: "New",
    parentId: null,
    slug: "new",
    imageBannerUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/YZkL00434Z2UF6nrVBEYs/5481ea18af3966d5db2120e9e69964dd/NEW.jpg",
    imageThumbnailUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/1XgF0NTfcIHurGGC11JSfW/4201d94d1e46a495f52aa9b6bc4fb315/Mobile-New-Arrivals.jpg",
    showInDesktopNav: true,
    showInMobileNav: true,
  },
  {
    id: "101",
    name: "Pants & Jeans",
    parentId: "100",
    slug: "new-pants-and-jeans",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "102",
    name: "Shirts",
    parentId: "100",
    slug: "new-shirts",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "103",
    name: "Sweaters",
    parentId: "100",
    slug: "new-sweaters",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "104",
    name: "Outerwear",
    parentId: "100",
    slug: "new-outerwear",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "105",
    name: "Shorts & Swim",
    parentId: "100",
    slug: "new-shorts-and-swim",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "106",
    name: "T-Shirts, Henleys & Polos",
    parentId: "100",
    slug: "new-tops",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "107",
    name: "Golf",
    parentId: "100",
    slug: "new-golf",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "108",
    name: "Suits & Blazers",
    parentId: "100",
    slug: "new-suits-and-blazers",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "109",
    name: "Accessories",
    parentId: "100",
    slug: "new-accessories",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "200",
    name: "Sale",
    parentId: null,
    slug: "sale",
    imageBannerUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/1RRgN6lY74bOu7sHauNNGF/3ce2903ba1e082f5686a4be7654a2b17/Sale.jpg",
    imageThumbnailUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/5P9QYuaQnmXoghIawOAbBJ/645194b05735ecf4e436a9abc046e65a/Mobile-Sale.jpg",
    showInDesktopNav: false,
    showInMobileNav: true,
  },
  {
    id: "201",
    name: "Sale Shirts",
    parentId: "200",
    slug: "sale-shirts",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "202",
    name: "Sale Pants & Jeans",
    parentId: "200",
    slug: "sale-pants-and-jeans",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "203",
    name: "Sale T-Shirts, Henleys, Polos",
    parentId: "200",
    slug: "sale-tops",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "204",
    name: "Sale Shorts & Swim",
    parentId: "200",
    slug: "sale-shorts-and-swim",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "205",
    name: "Sale Golf",
    parentId: "200",
    slug: "sale-golf",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "206",
    name: "Sale Suits & Blazers",
    parentId: "200",
    slug: "sale-suits-and-blazers",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "207",
    name: "Sale Sweaters",
    parentId: "200",
    slug: "sale-sweaters",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "208",
    name: "Sale Outerwear",
    parentId: "200",
    slug: "sale-outerwear",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "209",
    name: "Sale Accessories",
    parentId: "200",
    slug: "sale-accessories",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "210",
    name: "Sale Extended Sizes",
    parentId: "200",
    slug: "sale-extended-sizes",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "300",
    name: "Pants & Jeans",
    parentId: null,
    slug: "pants-and-jeans",
    imageBannerUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/3bulXahAUrzfgeoiGKZ8K5/6136018f02a4c783a2f24dcfd17aca39/Pants___Jeans.jpg",
    imageThumbnailUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/2iOgVeGvEYQiJOwtatRYYo/acc9d65eaf8ecec652bf9af4d242e394/Mobile-Pants.jpg",
    showInDesktopNav: true,
    showInMobileNav: true,
  },
  {
    id: "301",
    name: "Chinos",
    parentId: "300",
    slug: "pants-chinos",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "302",
    name: "Jeans",
    parentId: "300",
    slug: "pants-jeans",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "303",
    name: "Athletic Pants & Joggers",
    parentId: "300",
    slug: "pants-athletic",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "304",
    name: "Dress Pants",
    parentId: "300",
    slug: "pants-formal",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "305",
    name: "Golf Pants",
    parentId: "300",
    slug: "pants-golf",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "306",
    name: "Pants in Extended Sizes",
    parentId: "300",
    slug: "pants-extended-sizes",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "400",
    name: "Shirts",
    parentId: null,
    slug: "shirts",
    imageBannerUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/bODpqNlwbcCBanUFK0GEH/daafd6c224a6634aa8e3ea642bcbf8ec/Shirts.jpg",
    imageThumbnailUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/5dg6gvI0d84RXsp8qd0nlr/9f9ca47a944b5594f8eb7f3941b0d74f/Mobile-Shirts.jpg",
    showInDesktopNav: true,
    showInMobileNav: true,
  },
  {
    id: "401",
    name: "Short Sleeve Shirts",
    parentId: "400",
    slug: "shirts-short-sleeves",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "402",
    name: "Casual Shirts",
    parentId: "400",
    slug: "shirts-casual",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "403",
    name: "Business Casual Shirts",
    parentId: "400",
    slug: "shirts-business-casual",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "404",
    name: "Dress Shirts",
    parentId: "400",
    slug: "shirts-formal",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "405",
    name: "T-Shirts, Henleys & Polos",
    parentId: "400",
    slug: "shirts-tops",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "406",
    name: "Sweaters",
    parentId: "400",
    slug: "shirts-sweaters",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "407",
    name: "Shirts in Extended Sizes",
    parentId: "400",
    slug: "shirts-extended-sizes",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "500",
    name: "Shorts & Swim",
    parentId: null,
    slug: "shorts-and-swim",
    imageBannerUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/NPoaQhnYLwHDkktfVMD3H/d5ebc70b905e847e2f482a1b22154945/Shorts___Swim.jpg",
    imageThumbnailUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/FX1mnuzZWWeN03dkSeHkP/ca0c24409b087c5c2bd96f5ff523fb61/Mobile-shorts_Swim.jpg",
    showInDesktopNav: true,
    showInMobileNav: true,
  },
  {
    id: "501",
    name: "Chino Shorts",
    parentId: "500",
    slug: "shorts-and-swim-chinos",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "502",
    name: "Casual Shorts",
    parentId: "500",
    slug: "shorts-and-swim-casual",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "503",
    name: "Swim Trunks",
    parentId: "500",
    slug: "shorts-and-swim-swimming",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "504",
    name: "Golf Shorts",
    parentId: "500",
    slug: "shorts-and-swim-golf",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "505",
    name: "Shorts & Swim in Extended Sizes",
    parentId: "500",
    slug: "shorts-and-swim-extended-sizes",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "600",
    name: "Golf",
    parentId: null,
    slug: "golf",
    imageBannerUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/3mpr4SsyyMzgSfhiQF0eTC/f43b0f0e4b9f552ad3d35c5274fbad5d/Golf.jpg",
    imageThumbnailUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/24GjedjQFC5w8cfiJaaNne/6891107f48e9a7c4c9f12d24b150fdb3/Mobile-Golf.jpg",
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "601",
    name: "Golf Tops",
    parentId: "600",
    slug: "golf-tops",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "602",
    name: "Golf Pants",
    parentId: "600",
    slug: "golf-pants",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "603",
    name: "Golf Shorts",
    parentId: "600",
    slug: "golf-shorts",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "604",
    name: "Golf Belts",
    parentId: "600",
    slug: "golf-belts",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "605",
    name: "Golf in Extended Sizes",
    parentId: "600",
    slug: "golf-extended-sizes",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "700",
    name: "Sweaters",
    parentId: null,
    slug: "sweaters",
    imageBannerUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/3cUDD93qmYyo5gAbDGJBdB/b9844b9d948786299cba6a3f639a3da5/Sweaters.jpg",
    imageThumbnailUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/68W25oOVA3kqYGR7IPGSQO/23d0436b87259360786518a5761764c1/Mobile-Sweaters.jpg",
    showInDesktopNav: true,
    showInMobileNav: true,
  },
  {
    id: "701",
    name: "Crew & V-Neck Sweaters",
    parentId: "700",
    slug: "sweaters-crew-neck",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "702",
    name: "Half & Full Zip Sweaters",
    parentId: "700",
    slug: "sweaters-zip",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "703",
    name: "Henley, Turtleneck & Cardigan Sweaters",
    parentId: "700",
    slug: "sweaters-henleys",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "704",
    name: "Sweatshirts & Fleece",
    parentId: "700",
    slug: "sweaters-fleece",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "800",
    name: "Suits & Blazers",
    parentId: null,
    slug: "suits-and-blazers",
    imageBannerUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/6w484UQmTiEMKMYK5AtcXF/70310a9d1015e7653eb8aa5a47c1ab14/Wedding_Guest.jpg",
    imageThumbnailUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/pJFeCJk6h4DLsJqsVXdtq/0e39e7cbfa0351991d9a3cbc829e1ecd/Mobile-Suits-Blazer.jpg",
    showInDesktopNav: true,
    showInMobileNav: true,
  },
  {
    id: "801",
    name: "Suits",
    parentId: "800",
    slug: "suits-and-blazers-formal",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "802",
    name: "Blazers & Sport Coats",
    parentId: "800",
    slug: "suits-and-blazers-informal",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "803",
    name: "Tuxedos",
    parentId: "800",
    slug: "suits-and-blazers-gala",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "804",
    name: "Suits & Blazers in Extended Sizes",
    parentId: "800",
    slug: "suits-and-blazers-extended-sizes",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "805",
    name: "Groomshop",
    parentId: "800",
    slug: "suits-and-blazers-groomshop",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "806",
    name: "Guest Attire",
    parentId: "800",
    slug: "suits-and-blazers-guest-attire",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "900",
    name: "Outerwear",
    parentId: null,
    slug: "outerwear",
    imageBannerUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/5pxzTiYOy0guenxcxs1ikd/9e18de3c0d90197ea96b890be2423722/Outerwear.jpg",
    imageThumbnailUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/3O3SKk4YjkD41HkZnwsxsC/eabfc6d7adbd8b22be8bafe37f94b99b/Mobile-Outerwear.jpg",
    showInDesktopNav: true,
    showInMobileNav: true,
  },
  {
    id: "901",
    name: "Jackets & Coats",
    parentId: "900",
    slug: "outerwear-jackets",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "902",
    name: "Bombers",
    parentId: "900",
    slug: "outerwear-bombers",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "903",
    name: "Vests",
    parentId: "900",
    slug: "outerwear-vests",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "904",
    name: "Blazers & Sport Coats",
    parentId: "900",
    slug: "outerwear-sports",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "1000",
    name: "Accessories",
    parentId: null,
    slug: "accessories",
    imageBannerUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/2OdZMe0lrqaffPRgiVXcC5/128736329b7d67340c3f3b0c120f730b/Accessories.jpg",
    imageThumbnailUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/5UBSXHj1GSR1qttYEe8avK/c55d1873c36d15529f75dcf3cfe98309/Mobile-Accessories.jpg",
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "1001",
    name: "Hats & Gloves",
    parentId: "1000",
    slug: "accessories-hats",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "1002",
    name: "Ties & Pocket Squares",
    parentId: "1000",
    slug: "accessories-ties",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "1003",
    name: "Socks",
    parentId: "1000",
    slug: "accessories-socks",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "1004",
    name: "Belts",
    parentId: "1000",
    slug: "accessories-belts",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "1005",
    name: "Gift Cards",
    parentId: "1000",
    slug: "accessories-gift-cards",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "1100",
    name: "Extended Sizes",
    parentId: null,
    slug: "extended-sizes",
    imageBannerUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/YZkL00434Z2UF6nrVBEYs/5481ea18af3966d5db2120e9e69964dd/NEW.jpg",
    imageThumbnailUrl:
      "https://bonobos-contentful.imgix.net/1zbm708fksg8/VT6mGQMulQx4HlOINqiAV/8a5514d40bc65f6de2e805ad64563a65/Mobile-Shirts.jpg",
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "1101",
    name: "Pants & Jeans",
    parentId: "1100",
    slug: "extended-sizes-pants",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "1102",
    name: "Shirts",
    parentId: "1100",
    slug: "extended-sizes-shirts",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "1103",
    name: "Shorts & Swim",
    parentId: "1100",
    slug: "extended-sizes-shorts",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "1104",
    name: "Suits & Blazers",
    parentId: "1100",
    slug: "extended-sizes-suits",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "1105",
    name: "Sweaters & Polos",
    parentId: "1100",
    slug: "extended-sizes-sweaters",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "1106",
    name: "Golf",
    parentId: "1100",
    slug: "extended-sizes-golf",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
  {
    id: "1107",
    name: "Accessories",
    parentId: "1100",
    slug: "extended-sizes-accessories",
    imageBannerUrl: null,
    imageThumbnailUrl: null,
    showInDesktopNav: false,
    showInMobileNav: false,
  },
];
